### ISSUE TITLE
Merge DittoCSharpTools and DittoDotnetTools into a single repo

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoCSharpTools#4]

**Comment by busec0** [comment]
1. https://github.com/getditto/DittoDotnetTools made public 
2. Copied and slightly refactored Heartbeat from here https://github.com/getditto/DittoDotnetTools/tree/main/DittoHeartbeat (just moved some things around and added JSON deserialization)
3. Replaced the sample with a .NET MAUI one, in the same app with the PresenceViewer (like Swift). 
4. Duplicated existing issues (and added some more) 

@bplattenburg this issue can be closed and the repo archived. 

 
![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-04 at 19 33 15](https://github.com/getditto/DittoCSharpTools/assets/26183235/dc119cee-3d89-4422-aa5d-e97a6d3a4bfc)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-04 at 19 33 17](https://github.com/getditto/DittoCSharpTools/assets/26183235/14716e2a-6216-4b78-9060-3234631a1563)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-04 at 19 34 04](https://github.com/getditto/DittoCSharpTools/assets/26183235/06c71ced-2dbd-4b02-b947-2092c7c365cf)

**Comment by bplattenburg** [comment]
@busec0 Thank you!
